apps/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('all/', views.MemberListView.as_view(), name='member-list'),
    path('add/', views.AddMemberView.as_view(), name='add-member'),
    path('<int:pk>/detail/', views.MemberDetailView.as_view(),
         name='detail-member'),
    path('<int:pk>/update/', views.UpdateMemberView.as_view(), name='update-member'),
    path('<int:pk>/del/', views.DeleteMemberView.as_view(), name='delete-member')
]

apps/reports/urls.py
from django.urls import path
from . import views
import calendar

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='gen-reports'),
    path('export/', views.export_all, name='export'),
    path('export/<int:pk>/member/', views.export_single, name='export-single'),
]

gymrocket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.members.views import LandingPage
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),

    # App routes
    path('members/', include("apps.members.urls", namespace="members")),
    path('wallpaper/', include("apps.wallpaper.urls", namespace="wallpaper")),
    path('reports/', include("apps.reports.urls", namespace="reports")),
    path('dashboard/', include("apps.dashboard.urls", namespace="dashboard")),

    # Landing Page route
    path('', LandingPage.as_view(), name="landing-page"),

    # password change routes
    path('password_change/', PasswordChangeView.as_view(), name='password-change'),
    path('password_change_done/', PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # auth routes
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

# for handling profile photos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handling Static files in Debug mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/reports/models.py
from django.db import models
from django.forms import ModelForm
from django.db import models
import datetime
import calendar

YEAR_CHOICES = []
for year in range(2020, (datetime.datetime.now().year + 5)):
    YEAR_CHOICES.append((year, year))

BATCH = (
    ('morning', 'Morning'),
    ('evening', 'Evening'),
    ('', 'All')
)

MONTHS_CHOICES = tuple(
    zip(range(1, 13), (calendar.month_name[i] for i in range(1, 13))))


class GenerateReports(models.Model):
    # Reports model to generate reports according to year, month and batch
    month = models.IntegerField(
        choices=MONTHS_CHOICES, default=datetime.datetime.now().year, blank=True)
    year = models.IntegerField(
        choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    batch = models.CharField(
        max_length=30,
        choices=BATCH,
        default=BATCH[2][0],
        blank=True)


class GenerateReportForm(ModelForm):
    # Report Form
    class Meta:
        model = GenerateReports
        fields = '__all__'

apps/reports/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import csv
from apps.members.models import Member
from .models import GenerateReportForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def export_all(user_obj):
    # Generate Users.csv file with Report Data generated by Query
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'
    writer = csv.writer(response)
    writer.writerow(['First name', 'Last name', 'DOB', 'Mobile',
                     'Admission Date', 'Subscription Type', 'Batch'])
    members = user_obj.values_list('first_name', 'last_name', 'dob',
                                   'mobile_number', 'admitted_on', 'subscription_type', 'batch')
    # print(members)
    for user in members:
        writer.writerow(user)

    return response


@login_required
# Export Single User Data in CSV format, called on user profile view
def export_single(request, pk):
    member = Member.objects.filter(pk=pk)
    return export_all(member)


@login_required
def reports(request):
    """ Generate reports according to year, month and batch
    Year Range = 2020 - Current Year + 5 (Changed in Model)
    Month Range - 1 - 12
    Batch - Mor, Eve & Both

    export_all function is used to generate reports in .CSV (Excel Formats)
    """
    if request.method == 'POST':
        form = GenerateReportForm(request.POST)
        if form.is_valid():
            year = request.POST.get('year')
            month = request.POST.get('month')
            batch = request.POST.get('batch')

            if month and year and batch:
                query = f"SELECT * FROM members_member WHERE YEAR(registration_date)='{year}' AND MONTH(registration_date)='{month}' AND batch='{batch}' LIMIT 1000"
            elif month and year:
                query = f"SELECT * FROM members_member WHERE YEAR(registration_date)='{year}' AND MONTH(registration_date)='{month}' LIMIT 1000"
            elif month and batch:
                query = f"SELECT * FROM members_member WHERE MONTH(registration_date)='{month}' AND batch='{batch}' LIMIT 1000"
            elif year and batch:
                query = f"SELECT * FROM members_member WHERE YEAR(registration_date)='{year}' AND batch='{batch}' LIMIT 1000"
            else:
                query = f"SELECT * FROM members_member WHERE YEAR(registration_date)='{year}' LIMIT 1000"
            with connection.cursor() as cursor:
                cursor.execute(query)
                users = dictfetchall(cursor)
                for user in users:
                    user.update({
                        'pk': user['member_id']
                    })
            if 'export' in request.POST:
                return export_all(users)
            context = {
                'users': users,
                'form': form,
            }
            return render(request, 'reports/export.html', context)
    else:
        form = GenerateReportForm()
    return render(request, 'reports/export.html', {'form': form})

apps/reports/templates/reports/export.html
{% extends "base.html" %} 
{% load static %}

{% load tailwind_filters %}

{% block title %}- Reports
{% endblock title %}

{% block content %}

<div class="transition duration-300 ease-in-out transform visible:-translate-y-1 hover:scale-90 bg-blue-100 text-blue-700 px-4 py-3 mt-3 mb-2 hidden" role="alert" id="alert-div">
  <p class="font-bold text-center">You can't view and export the query together</p>
  <p class="text-sm text-center">If you viewed query, reload and select export this time.</p>
</div>
<div class="flex justify-end">
  <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow mt-2 mt-2" title="Reload" id="reloadBtn">
    Reload</button>
</div>

<div class="max-w-3xl mx-auto">
  <div class="flex justify-center">
    <h2 class="mt-3 mb-4 text-4xl leading-7 text-gray-900 sm:text-3xl sm:truncate font-mono">
      Generate Reports
    </h2>
  </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="mb-5 w-full bg-gray-800 hover:bg-gray-900 px-3 py-2 rounded-md text-white" type="submit">View Query</button>
        <button class="mb-5 w-full bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md text-white" type="submit" id="export" name="export">Export</button>
    </form>



{% if users %}
<div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Name
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  batch
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Amount
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Registration Upto
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Subscription Type
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Subscription Period
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Status
                </th>
                <th scope="col" class="relative px-6 py-3">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            {% for member in users %}
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <div class="flex-shrink-0 h-10 w-10">
                        {% if member.photo %}
                        <img class="h-10 w-10 rounded-full" src="{{ member.photo }}" alt="profilepic">
                        {% else %}
                        <img class="h-10 w-10 rounded-full" src="/media/default.jpg" alt="defaultprofile-pic">
                        {% endif %}

                    </div>
                    <div class="ml-4">
                      <div class="text-sm font-medium text-gray-900">
                        <a href="{% url 'members:detail-member' member.pk %}">
                        {{ member.first_name }} {{ member.last_name }}
                        </a>
                      </div>
                      <div class="text-sm text-gray-500">
                        {{ member.email }}
                      </div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ member.batch }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ member.amount }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ member.registration_upto }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">{{ member.subscription_type }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    {{ member.subscription_period }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                    {% if member.fee_status == 'paid' %}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        {{ member.fee_status }}
                    </span>
                        {% else %}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                        {{ member.fee_status }}
                    </span>
                    {% endif %}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <a href="{% url 'members:update-member' member.pk %}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                </td>
              </tr>
              {% endfor %}
              <!-- More items... -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endif %}
{% endblock content %}

{% block script %}
<script>
  let reports = document.getElementById('reports');
  let reportsMobile = document.getElementById('reports-mobile')
  reports.classList.add('bg-gray-900','text-white')
  reportsMobile.classList.add('bg-gray-900','text-white')

  let reloadBtn = document.getElementById('reloadBtn');
  reloadBtn.onclick = () => location.reload();

  let alertDiv = document.getElementById('alert-div');
  let exportBtn = document.getElementById('export');
  exportBtn.addEventListener('click', function () {
    alertDiv.classList.toggle('hidden');
  setTimeout(() => {
    alertDiv.classList.toggle('hidden');
  }, 10000);
  })

</script>
{% endblock script %}