apps/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('all/', views.MemberListView.as_view(), name='member-list'),
    path('add/', views.AddMemberView.as_view(), name='add-member'),
    path('<int:pk>/detail/', views.MemberDetailView.as_view(),
         name='detail-member'),
    path('<int:pk>/update/', views.UpdateMemberView.as_view(), name='update-member'),
    path('<int:pk>/del/', views.DeleteMemberView.as_view(), name='delete-member')
]

apps/reports/urls.py
from django.urls import path
from . import views
import calendar

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='gen-reports'),
    path('export/', views.export_all, name='export'),
    path('export/<int:pk>/member/', views.export_single, name='export-single'),
]

gymrocket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.members.views import LandingPage
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),

    # App routes
    path('members/', include("apps.members.urls", namespace="members")),
    path('wallpaper/', include("apps.wallpaper.urls", namespace="wallpaper")),
    path('reports/', include("apps.reports.urls", namespace="reports")),
    path('dashboard/', include("apps.dashboard.urls", namespace="dashboard")),

    # Landing Page route
    path('', LandingPage.as_view(), name="landing-page"),

    # password change routes
    path('password_change/', PasswordChangeView.as_view(), name='password-change'),
    path('password_change_done/', PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # auth routes
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

# for handling profile photos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handling Static files in Debug mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/members/models.py
from django.db import models
from datetime import date


SUBSCRIPTION_TYPE_CHOICES = (
    ('gym', 'Gym'),
    ('cross_fit', 'Cross Fit'),
    ('gym_and_cross_fit', 'Gym + Cross Fit'),
    ('pt', 'Personal Training')
)

SUBSCRIPTION_PERIOD_CHOICES = (
    ('1', '1 Month'),
    ('2', '2 Months'),
    ('3', '3 Months'),
    ('4', '4 Months'),
    ('5', '5 Months'),
    ('6', '6 Months'),
    ('7', '7 Months'),
    ('8', '8 Months'),
    ('9', '9 Months'),
    ('10', '10 Months'),
    ('11', '11 Months'),
    ('12', '12 Months'),
)

FEE_STATUS = (
    ('paid', 'Paid'),
    ('pending', 'Pending'),
)

STATUS = (
    (0, 'Start'),
    (1, 'Stop'),
)

BATCH = (
    ('morning', 'Morning'),
    ('evening', 'Evening'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other')
)


class Member(models.Model):
    """ Initial Member Model """
    member_id = models.AutoField(primary_key=True)
    first_name = models.CharField(('First Name'), max_length=50)
    last_name = models.CharField(('Last Name'), max_length=50)
    gender = models.CharField(
        ('Gender'), choices=GENDER, max_length=7)
    mobile_number = models.CharField(
        ('Mobile Number'), max_length=10, unique=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=300, blank=True)
    medical_history = models.CharField(
        ('Medical History'), max_length=300, blank=True, default='None')
    admitted_on = models.DateField(auto_now_add=True)
    registration_date = models.DateField(
        ('Registration Date'))
    registration_upto = models.DateField()
    dob = models.DateField()
    subscription_type = models.CharField(
        ('Subscription Type'),
        max_length=30,
        choices=SUBSCRIPTION_TYPE_CHOICES,
        default=SUBSCRIPTION_TYPE_CHOICES[0][0]
    )
    subscription_period = models.CharField(
        ('Subscription Period'),
        max_length=30,
        choices=SUBSCRIPTION_PERIOD_CHOICES,
        default=SUBSCRIPTION_PERIOD_CHOICES[0][0]
    )
    amount = models.CharField(max_length=30)
    fee_status = models.CharField(
        ('Fee Status'),
        max_length=30,
        choices=FEE_STATUS,
        default=FEE_STATUS[0][0]
    )
    batch = models.CharField(
        max_length=30,
        choices=BATCH,
        default=BATCH[0][0]
    )
    photo = models.FileField(upload_to='photos/', blank=True)
    stop = models.IntegerField(
        ('Status'), choices=STATUS, default=STATUS[0][0], blank=True)

    def calculate_age(self):
        today = date.today()
        return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

    @property
    def get_month(self):
        return int(self.registration_date.strftime("%m"))

    def __str__(self):
        return self.first_name + ' ' + self.last_name

apps/members/forms.py
import dateutil.relativedelta as delta

from datetime import datetime
from django import forms
from .models import Member
from django.db import connection


class AddMemberForm(forms.ModelForm):
    # Add new Member form
    class Meta:
        model = Member
        fields = '__all__'
        exclude = ['registration_upto']

        widgets = {
            'registration_date': forms.DateInput(attrs={'type': 'date'}),
            'address': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'medical_history': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'dob': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}),
            'photo': forms.FileInput(attrs={'accept': 'image/*;capture=camera'})
        }

    def clean_mobile_number(self, *args, **kwargs):
        # Check for mobile number and return Validation Error if incorrect
        mobile_number = self.cleaned_data.get('mobile_number')
        if not mobile_number.isdigit():
            raise forms.ValidationError('Mobile number should be a number')
        if Member.objects.filter(mobile_number=mobile_number).exists():
            raise forms.ValidationError(
                'This mobile number has already been registered.')
        else:
            if len(str(mobile_number)) == 10:
                return mobile_number
            else:
                raise forms.ValidationError(
                    'Mobile number should be 10 digits long.')
        return mobile_number

    def save(self, commit=True):
        """
        Save this form's self.instance object if commit=True. Otherwise, add
        a save_m2m() method to the form which can be called after the instance
        is saved manually at a later time. Return the model instance.
        """
        if self.errors:
            raise ValueError(
                "The %s could not be %s because the data didn't validate." % (
                    self.instance._meta.object_name,
                    'created' if self.instance._state.adding else 'changed',
                )
            )
        if commit:
            # If committing, save the instance and the m2m data immediately.
            if isinstance(self.instance, Member):
                data = self.cleaned_data
                data['photo'] = self.cleaned_data['photo'].name
                data['registration_upto'] = self.cleaned_data['registration_date'] + delta.relativedelta(months=int(self.cleaned_data['subscription_period']))
                data['registration_date'] = self.cleaned_data['registration_date'].strftime('%Y-%m-%d')
                data['dob'] = self.cleaned_data['dob'].strftime('%Y-%m-%d')
                data['admitted_on'] = datetime.now().strftime('%Y-%m-%d')

                names = data.keys()
                values = [f"'{str(value)}'" for value in data.values()]
                
                with connection.cursor() as cursor:
                    sql = "INSERT INTO members_member ({0}) VALUES ({1})".format(", ".join(names), ", ".join(values))
                    cursor.execute(sql)
            else:
                raise ValueError("Exception in save method: self.instance is not a Member instance")
            self._save_m2m()
        else:
            # If not committing, add a method to the form to allow deferred
            # saving of m2m data.
            self.save_m2m = self._save_m2m
        return self.instance

    def clean_amount(self):
        # Clean money amount
        amount = self.cleaned_data.get('amount')
        if not amount.isdigit():
            raise forms.ValidationError('Amount should be a number')
        return amount

    def clean(self):
        # Check for already existing member
        cleaned_data = super().clean()
        dob = cleaned_data.get('dob')
        first_name = cleaned_data.get('first_name').capitalize()
        last_name = cleaned_data.get('last_name').capitalize()
        queryset = Member.objects.filter(
            first_name=first_name,
            last_name=last_name,
            dob=dob
        ).count()
        if queryset > 0:
            raise forms.ValidationError('This member already exists!')


class AddMemberUpdateForm(forms.ModelForm):
    # Update Member form without registration_upto date
    class Meta:
        model = Member
        fields = '__all__'
        exclude = ['registration_upto']

        widgets = {
            'registration_date': forms.DateInput(attrs={'type': 'date'}),
            'address': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'medical_history': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'dob': forms.DateInput(attrs={'class': 'datepicker', 'type': 'date'}),
            'photo': forms.FileInput(attrs={'accept': 'image/*;capture=camera'})
        }

    def save(self, commit=True):
        """
        Save this form's self.instance object if commit=True. Otherwise, add
        a save_m2m() method to the form which can be called after the instance
        is saved manually at a later time. Return the model instance.
        """
        if self.errors:
            raise ValueError(
                "The %s could not be %s because the data didn't validate." % (
                    self.instance._meta.object_name,
                    'created' if self.instance._state.adding else 'changed',
                )
            )
        if commit:
            # If committing, save the instance and the m2m data immediately.
            if isinstance(self.instance, Member):
                data = self.cleaned_data
                data['photo'] = self.cleaned_data['photo'].name
                data['registration_date'] = self.cleaned_data['registration_date'].strftime('%Y-%m-%d')
                data['dob'] = self.cleaned_data['dob'].strftime('%Y-%m-%d')
   
                values = [f"{name} = '{value}'" for name, value in data.items()]
                
                with connection.cursor() as cursor:
                    sql = "UPDATE members_member SET {0} WHERE member_id = {1}".format(", ".join(values), self.instance.pk)
                    cursor.execute(sql)
            else:
                raise ValueError("Exception in save method: self.instance is not a Member instance")
            self._save_m2m()
        else:
            # If not committing, add a method to the form to allow deferred
            # saving of m2m data.
            self.save_m2m = self._save_m2m
        return self.instance

apps/members/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, DeleteView, ListView
from .models import Member
from .forms import AddMemberForm, AddMemberUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
import dateutil.relativedelta as delta
from django.urls import reverse
from apps.wallpaper.models import Wallpaper
from apps.payments.models import Payments
from django.db import connection


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


class LandingPage(TemplateView):
    # Landing Page - CRUD wallpaper model
    template_name = "landing_page.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT photo FROM wallpaper_wallpaper LIMIT 0, 1000;")
            if cursor.rowcount > 0:
                wallpaper = cursor.fetchone()[0]
        
                context.update({
                    'wallpaper': {
                        "photo": wallpaper
                    }
                })
        return context


class MemberListView(LoginRequiredMixin, ListView):
    """ Login Required -  List Member by first_name
        Also show stopped members to undo changes
    """
    template_name = 'members/view_members.html'
    context_object_name = 'data'
    paginate_by = 8

    def get_queryset(self):
        #members = Member.objects.filter(stop=0).order_by('first_name')
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM members_member WHERE stop=0 ORDER BY (first_name) LIMIT 0, 1000;")
            members = dictfetchall(cursor)
            for member in members:
                member.update({
                    'pk': member['member_id']
                })
            return members

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        with connection.cursor() as cursor:
            stopped_members = cursor.execute("SELECT * FROM members_member WHERE stop=1 ORDER BY (first_name) LIMIT 0, 1000;")
            members = dictfetchall(cursor)
            for member in members:
                member.update({
                    'pk': member['member_id']
                })
            context.update({
                'stopped_member_data': stopped_members
            })
        return context


class AddMemberView(LoginRequiredMixin, CreateView):
    """ Login Required - Add new member view with 'AddMemberForm' form class
        form_valid method extract relative date form subscription_period and extends registration_upto data accordingly
        Generates a Payment Model Object if status is set to paid
    """
    template_name = 'members/add_member.html'
    form_class = AddMemberForm

    def get_success_url(self) -> str:
        return reverse("members:member-list")

    def form_valid(self, form):
        form.instance.registration_upto = form.cleaned_data['registration_date'] + delta.relativedelta(
            months=int(form.cleaned_data['subscription_period']))
        self.object = form.save()

        if form.cleaned_data['fee_status'] == 'paid':
            payments = Payments(
                user=self.object,
                payment_date=form.cleaned_data['registration_date'],
                payment_period=form.cleaned_data['subscription_period'],
                payment_amount=form.cleaned_data['amount'])

            with connection.cursor() as cursor:
                cursor.execute(f"INSERT INTO payments_payments VALUES ({payments.user.pk}, {payments.payment_date}, {payments.payment_period}, {payments.payment_amount})")

        return HttpResponseRedirect(self.get_success_url())


class MemberDetailView(LoginRequiredMixin, DetailView):
    """ Login Required - Detail View to show personal and medical information of Member
        Also Displays any payment history if available
    """
    template_name = 'members/member_detail.html'
    context_object_name = 'member'
    queryset = Member.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        payments = Payments.objects.filter(user=self.kwargs['pk'])
        if not payments.exists():
            payments = 'No Records'
        context.update({
            'member_payment': payments
        })
        return context


class UpdateMemberView(LoginRequiredMixin, UpdateView):
    """ Login Required - Update Selected Member Data
        Reset relative data accordingly
        Checks for existing payment information with new data and creates if the new data has no record
    """
    template_name = 'members/update_member.html'
    form_class = AddMemberUpdateForm
    queryset = Member.objects.all()

    def get_success_url(self) -> str:
        return reverse("members:member-list")

    def form_valid(self, form):
        form.instance.registration_upto = form.cleaned_data['registration_date'] + delta.relativedelta(
            months=int(form.cleaned_data['subscription_period']))
        self.object = form.save()

        if form.cleaned_data['fee_status'] == 'paid':
            check = Payments.objects.filter(
                payment_date=form.cleaned_data['registration_date'], user=self.object).count()
            if check == 0:
                payments = Payments(
                    user=self.object,
                    payment_date=form.cleaned_data['registration_date'],
                    payment_period=form.cleaned_data['subscription_period'],
                    payment_amount=form.cleaned_data['amount'])
                payments.save()

        return HttpResponseRedirect(self.get_success_url())


class DeleteMemberView(LoginRequiredMixin, DeleteView):
    """ Delete Member Data """
    template_name = 'members/member_delete.html'
    queryset = Member.objects.all()

    def get_success_url(self) -> str:
        return reverse("members:member-list")

apps/members/templates/members/member_delete.html
{% extends "base.html" %} 
{% load static %} 
{% load tailwind_filters %}

{% block title %} Delete Member {% endblock title %}

{% block content %} 
    <div class="max-w-lg mx-auto mt-5">
        <h2 class="text-xl font-medium font-mono">Are you sure you want to delete the lead <i>'{{ member }}'</i> ?</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.crispy }}
            <button class="w-1/4 mt-3 ml-auto text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded" type="submit">Submit</button>
        </form>

    <div class="mt-5 py-5 border-t border-gray-200">
        <a href="{% url 'members:member-list' %}" class="hover:text-indigo-500 mt-3">Go Back To Members</a>
    </div>
    </div>
{% endblock content %}

apps/members/templates/members/member_detail.html
{% extends "base.html" %} 
{% load static %} 

{% block title %}Member - {{ member.first_name }} {% endblock title %} 

{% block content %} 
<div class="container mx-auto my-5 p-5">
    <div class="md:flex no-wrap md:-mx-2 ">
        <!-- Left Side -->
        <div class="w-full md:w-3/12 md:mx-2">
            <!-- Profile Card -->
            <div class="bg-white p-3 border-t-4 border-green-400">
                <div class="image overflow-hidden">
                    {% if member.photo %}
                    <img class="h-auto w-full mx-auto"
                        src="{{ member.photo.url }}"
                        alt="member-photo">
                    {% else %}
                    <img class="h-auto w-full mx-auto"
                        src="/media/default.jpg"
                        alt="member-photo">
                    {% endif %}
                </div>
                <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">{{ member.first_name|capfirst }} {{ member.last_name|capfirst }}</h1>
                <h3 class="text-gray-600 font-lg text-semibold leading-6">Medical History</h3>
                <p class="text-sm text-gray-500 hover:text-gray-600 leading-6">{{ member.medical_history }}</p>
                <ul
                    class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
                    <li class="flex items-center py-3">
                        <span>Fee Status</span>
                        {% if member.fee_status == 'paid' %}
                        <span class="ml-auto"><span
                                class="bg-green-500 py-1 px-2 rounded text-white text-sm">Paid</span></span>
                        {% else %} 
                        <span class="ml-auto"><span 
                            class="bg-red-500 py-1 px-2 rounded text-white text-sm">Pending</span></span>
                        {% endif %}
                    </li>
                    <li class="flex items-center py-3">
                        <span>Member since</span>
                        <span class="ml-auto">{{ member.registration_date|date:"d/M/Y" }}</span>
                    </li>
                </ul>
            </div>
            <div class="my-4"></div>

        </div>

        <div class="w-full md:w-9/12 mx-2 h-64">
            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                    <span clas="text-green-500">
                        <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                    </span>
                    <span class="tracking-wide">Personal Information</span>
                </div>
                <div class="text-gray-700">
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">First Name</div>
                            <div class="px-4 py-2">{{ member.first_name|capfirst }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Last Name</div>
                            <div class="px-4 py-2">{{ member.last_name|capfirst }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Gender</div>
                            <div class="px-4 py-2">{{ member.gender }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Contact No.</div>
                            <div class="px-4 py-2">+91 {{ member.mobile_number }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Current Address</div>
                            <div class="px-4 py-2">{{ member.address }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Email.</div>
                            <div class="px-4 py-2">
                                <a class="text-blue-800" href="mailto:{{ member.email }}">{{ member.email }}</a>
                            </div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Birthday</div>
                            <div class="px-4 py-2">Feb 06, 1998</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Age</div>
                            <div class="px-4 py-2">{{ member.calculate_age }} years old.</div>
                        </div>
                    </div>
                </div>
                <div class="flex justify-center">
                    <button 
                        class="block w-full text-blue-800 text-sm font-semibold rounded-lg hover:bg-gray-100 focus:outline-none focus:shadow-outline focus:bg-gray-100 hover:shadow-xs p-3 my-4"><a href="{% url 'members:delete-member' member.pk %}">Delete</a></button>
                    <button 
                        class="block w-full text-blue-800 text-sm font-semibold rounded-lg hover:bg-gray-100 focus:outline-none focus:shadow-outline focus:bg-gray-100 hover:shadow-xs p-3 my-4"><a href="{% url 'members:update-member' member.pk %}">Update</a></button>
                </div>
            </div>
            <!-- End of about section -->

            <div class="my-4"></div>

            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                    <span clas="text-green-500">
                        <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                    </span>
                    <span class="tracking-wide">Membership Information</span>
                </div>
                <div class="text-gray-700">
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Registration Date</div>
                            <div class="px-4 py-2">{{ member.registration_date|date:"D d M Y" }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Subscription Type</div>
                            <div class="px-4 py-2">{{ member.get_subscription_type_display }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Registration Upto</div>
                            <div class="px-4 py-2">{{ member.registration_upto|date:"D d M Y" }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Subscription Period</div>
                            <div class="px-4 py-2">{{ member.subscription_period }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Amount Paid</div>
                            <div class="px-4 py-2">₹ {{ member.amount }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Batch</div>
                            <div class="px-4 py-2">{{ member.batch }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Membership Status</div>
                            <div class="px-4 py-2">{{ member.stop }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Fee Status</div>
                            <div class="px-4 py-2">{{ member.fee_status }}</div>
                        </div>
                    </div>
                </div>
                    <button
                    class="block w-full text-blue-800 text-sm font-semibold rounded-lg hover:bg-gray-100 focus:outline-none focus:shadow-outline focus:bg-gray-100 hover:shadow-xs p-3 my-4" id="export" name="export"><a href="{% url 'reports:export-single' member.pk %}">Export</a></button>

            </div>
            {% if member_payment == 'No Records' %}
            <div class="bg-blue-100 text-blue-700 px-4 py-3 rounded" role="alert">
                <p class="font-bold text-center">No Payment History</p>
                <p class="text-sm text-center">These isn't any payments made by this member.</p>
              </div>
            {% else %}
            <!-- Payments Table -->
            <div class="flex justify-center">
                <h1 class="text-2xl mt-2 mb-2 font-semibold tracking-wide">Payment History</h1>
            </div>
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                  <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                      <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                          <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Payment Date
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Payment Period
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Amount
                            </th>
                          </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200">
                        {% for payment in member_payment %}
                          <tr>
                            <td class="px-6 py-4 whitespace-nowrap">
                              <div class="text-sm text-gray-900">{{ payment.payment_date }}</div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                {% if payment.payment_period == 1 %}
                                <div class="text-sm text-gray-900">{{ payment.payment_period }} month</div>
                                {% else %} 
                                <div class="text-sm text-gray-900">{{ payment.payment_period }} months</div>
                                {% endif %}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                              <div class="text-sm text-gray-900">₹ {{ member.amount }}</div>
                            </td>
                          </tr>
                          {% endfor %}
                          <!-- More items... -->
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            {% endif %}

            <!-- End of profile tab -->
        </div>
    </div>
</div>
</div>
{% endblock content %}