apps/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard, name="base"),
    path('memberchart/', views.member_chart, name="member-chart"),
    path('paymentchart/', views.payment_chart, name="payment-chart")
]

apps/members/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path('all/', views.MemberListView.as_view(), name='member-list'),
    path('add/', views.AddMemberView.as_view(), name='add-member'),
    path('<int:pk>/detail/', views.MemberDetailView.as_view(),
         name='detail-member'),
    path('<int:pk>/update/', views.UpdateMemberView.as_view(), name='update-member'),
    path('<int:pk>/del/', views.DeleteMemberView.as_view(), name='delete-member')
]

apps/reports/urls.py
from django.urls import path
from . import views
import calendar

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='gen-reports'),
    path('export/', views.export_all, name='export'),
    path('export/<int:pk>/member/', views.export_single, name='export-single'),
]

apps/wallpaper/urls.py
from django.urls import path
from . import views

app_name = "wallpaper"

urlpatterns = [
    path('change/', views.set_wallpaper, name='change')
]

gymrocket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.members.views import LandingPage
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),

    # App routes
    path('members/', include("apps.members.urls", namespace="members")),
    path('wallpaper/', include("apps.wallpaper.urls", namespace="wallpaper")),
    path('reports/', include("apps.reports.urls", namespace="reports")),
    path('dashboard/', include("apps.dashboard.urls", namespace="dashboard")),

    # Landing Page route
    path('', LandingPage.as_view(), name="landing-page"),

    # password change routes
    path('password_change/', PasswordChangeView.as_view(), name='password-change'),
    path('password_change_done/', PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # auth routes
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

# for handling profile photos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Handling Static files in Debug mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" content="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GymRocket {% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
        {% include 'navbar.html' %}
    <div class="max-w-7xl mx-auto">
        {% block content %}
        {% endblock content %}
    </div>
    
    
    
    {% block script %} 
    {% endblock script %}
    <script src="{% static 'js/test.js' %}"></script>
</body>
</html>

templates/landing_page.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-20 items-center justify-center flex-col">
      {% if wallpaper.photo %}
        <img class="lg:w-4/6 md:w-3/6 w-5/6 mb-7 object-cover object-center rounded" alt="hero" src="{{ wallpaper.photo }}">
      {% else %}
        <img class="lg:w-3/6 md:w-3/6 w-5/6 mb-7 object-cover object-center rounded" alt="hero" src="{% static 'images/wallpaper.jpg' %}">
      {% endif %}
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">RawFitness Gym Manager</h1>
        <div class="flex justify-center">
            {% if user.is_authenticated %}
          <button class="inline-flex text-white bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-900 rounded text-lg">
            <a href="{% url 'wallpaper:change' %}">Wallpaper</a></button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"> <a href="{% url 'members:member-list' %}">Members</a></button>
          {% else %}
          <button class="inline-flex text-white bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-900 rounded text-lg">
            <a href="{% url 'login' %}">LogIn</a></button>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/navbar.html
{% load static %}

<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false" id="mobileBtn">
          <span class="sr-only">Open main menu</span>
          <!-- Icon when menu is closed. -->
          <!--
            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Icon when menu is open. -->
          <!--
            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <a href="/"><img class="hidden lg:block h-8 w-auto" src="{% static 'images/p_logo.png' %}" alt="gymlogo"></a>
        </div>
        {% if user.is_authenticated %}
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4" id="nav">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'dashboard:base' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="dashboard-a">Dashboard</a>
            <a href="{% url 'members:add-member' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="add-mem">New Member</a>
            <a href="{% url 'members:member-list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="view-mem">Members</a>
            <a href="{% url 'reports:gen-reports' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="reports">Reports</a>
            <a href="{% url 'password-change' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" id="change-pass">Change Password</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
          </svg>
        </button>
        
        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
            <button class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <p class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"><a href="{% url 'logout' %}">Logout</a></p>
            </button>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  {% if user.is_authenticated %}
  <div class="hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="{% url 'dashboard:base' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" id="dashboard-mobile">Dashboard</a>
      <a href="{% url 'members:add-member' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" id="add-mem-mobile">New Member</a>
      <a href="{% url 'members:member-list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" id="view-mem-mobile">Members</a>
      <a href="{% url 'reports:gen-reports' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" id="reports-mobile">Reports</a>
      <a href="{% url 'password-change' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium" id="change-pass-mobile">Change Password</a>
    </div>
  </div>
  {% endif %}
</nav>

{% block script %}
<script>
  let mobBtn = document.getElementById('mobileBtn');
  let mobileMenu = document.getElementById('mobile-menu')
  mobBtn.addEventListener('click', function() {
    mobileMenu.classList.toggle('hidden');
  })
</script>
{% endblock script %}